Serial number: summary.serialNumber
Product class: summary.productClass
Software version: summary.softwareVersion
MAC: summary.mac
IP: summary.wanPppConnection.ExternalIPAddress
WLAN SSID: summary.wlanSsid
Connection username: summary.wanPppConnection.Username

